feature/EVUIK-148
evotor/Evo-UI-Kit pull request #1005
Opened 2021-09-22 09:21 UTC by Frommy

https://jira.evotor.ru/browse/EVUIK-148

2021-09-23 09:56 UTC, nilagor requested changes

2021-09-23 09:56 UTC, nilagor commented on projects/evo-ui-kit/src/lib/components/evo-counter/evo-counter.component.scss
> +    &__value {
в стилях сначала модификаторы блока должны идти, а потом элементы. 
то есть:

```
.evo-counter {
  ...
  &_sizes-small {...}
  &_disabled {...}
  &__value {...}
}
```

2021-09-23 09:56 UTC, nilagor commented on projects/evo-ui-kit/src/lib/components/evo-counter/evo-counter.component.ts
> +    get inputClasses(): { [cssClass: string]: boolean } {
почему input? здесь нет полей ввода. мб лучше `blockClasses` или `wrapClasses` например

2021-09-23 10:44 UTC, Frommy commented on projects/evo-ui-kit/src/lib/components/evo-counter/evo-counter.component.ts
> +    get inputClasses(): { [cssClass: string]: boolean } {
Увидел, что в другом месте inputClasses, подумал, что из-за того, что классы определяются по @input'ам.
Сделал blockClasses.

2021-09-23 10:45 UTC, Frommy commented on projects/evo-ui-kit/src/lib/components/evo-counter/evo-counter.component.scss
> +    &__value {
Сделал

2021-09-23 11:16 UTC, nilagor approved these changes

2021-10-01 10:17 UTC, merged

2021-10-01 10:20 UTC, andreymatveev commented
:tada: This PR is included in version 5.49.0 :tada:

The release is available on:
- [GitHub release](https://github.com/evotor/Evo-UI-Kit/releases/tag/v5.49.0)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: