feature/EVUIK-147
evotor/Evo-UI-Kit pull request #1006
Opened 2021-09-22 14:42 UTC by Frommy

2021-09-23 09:50 UTC, nilagor commented on src/stories/components/evo-badge.stories.ts
> +            margin-bottom: 10px;
offset строки съехал

2021-09-23 09:50 UTC, nilagor approved these changes

2021-09-23 11:12 UTC, Frommy commented on src/stories/components/evo-badge.stories.ts
> +                margin-bottom: 10px;
Поправил, в сторибуке в целом с форматированием сложно

2021-09-28 15:30 UTC, andreymatveev requested changes

2021-09-28 15:30 UTC, andreymatveev commented on src/stories/components/evo-badge.stories.ts
> +            colorsList: [
Этот список уже неактуальный

2021-10-01 10:16 UTC, merged

2021-10-01 10:20 UTC, andreymatveev commented
:tada: This PR is included in version 5.49.0 :tada:

The release is available on:
- [GitHub release](https://github.com/evotor/Evo-UI-Kit/releases/tag/v5.49.0)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: