Add components: navbar, dropdown, and let directive
evotor/Evo-UI-Kit pull request #1097
Opened 2023-01-16 10:04 UTC by harlamenko

2023-01-18 08:54 UTC, andreymatveev requested changes

2023-01-18 08:54 UTC, andreymatveev commented on projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navigation-item/evo-navbar-item.component.html
> +                class="evo-navbar__sub"
Максимальную высоту дропдауна можно было бы тоже ограничить (например, при помощи CSS-переменной, аналогично [автокомплиту](https://github.com/evotor/Evo-UI-Kit/blob/master/projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete.component.scss#L7)). 

В этом случае пункты должны скроллиться внутри дропдауна.

2023-01-18 11:53 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navigation-item/evo-navbar-item.component.scss
> +.evo-navbar__link {
так не работает 
![image](https://user-images.githubusercontent.com/37455526/213164860-736fd7de-5eff-4651-94dd-b27260a82f54.png)

2023-01-18 14:23 UTC, nilagor commented on projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navigation-item/evo-navbar-item.component.html
> +        [class]="isNested ? 'evo-navbar__link--nested' : 'evo-navbar__link'"
с учётом предыдущего коммента тебе здесь не нужен `evo-navbar__link` и эту строчку можно переписать конкретнее:

```
[class.evo-navbar__link_nested]="isNested"
```

2023-01-18 15:34 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navigation-item/evo-navbar-item.component.html
> +<ng-container *evoLet="$any(item) as linkItem">
версия typescript кита ругается, в более новых версиях, тайп гард работает нормально

2023-01-18 16:07 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +        this._positions = value ? [].concat(value).map(p => EVO_DROPDOWN_POSITION_DESCRIPTION[p] || p) : DEFAULT_POSITION;
ошибка, `Position = ('top-left' | 'top-center' | ...) | ConnectedPosition;` - так задумывалось.
нужно для того, чтобы иметь возможность использовать пресеты для некоторых кейсов, вместо постоянного формирования ConnectedPosition

2023-01-18 16:10 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +    @Input() needAutoScrollIntoViewIfOpen = false;
согласен, укорочу до `autoScrollIntoView`

2023-01-18 16:18 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +        if (!this.isOpen) {
ранний возврат поправлю.
scrollIntoView - не отражает полностью логику. от этого имени ты ожидаешь, что при вызове скролл будет происходить всегда, а логика это не удовлетворяет.

2023-01-18 16:19 UTC, nilagor commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +    @Output() isOpenChange = new EventEmitter<boolean>();
и по ссылке нет префикса. просто надо у `isOpen` его тоже убрать и будет красивое `[open]` и `(openChange)`

2023-01-18 16:21 UTC, nilagor commented on projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navigation-item/evo-navbar-item.component.html
> +<ng-container *evoLet="$any(item) as linkItem">
если просто внутри `<ng-container>` обращаться к полю компонента `item` ругается typescript? а на что ругается?

2023-01-18 16:29 UTC, nilagor commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +        this._positions = value ? [].concat(value).map(p => EVO_DROPDOWN_POSITION_DESCRIPTION[p] || p) : DEFAULT_POSITION;
мне показалось, что у тебя в `EvoPositionDescription` перечислены все возможные комбинации `ConnectedPosition` и нет такого кейса, когда может потребоваться генерация нового варианта, не?

но в целом да, в таком виде (ключ | кастомная позиция) идея как минимум имеет право на жизнь. 

я бы правда добавил ещё явную проверку на тип вместо попытки использовать объект как ключ другого объекта. код конечно станет менее изящным, но явное лучше чем не явное. что скажешь @andreymatveev ?

2023-01-18 16:39 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +        this._positions = value ? [].concat(value).map(p => EVO_DROPDOWN_POSITION_DESCRIPTION[p] || p) : DEFAULT_POSITION;
_"нет такого кейса, когда может потребоваться генерация нового варианта, не?"_
  в пресетах далеко не все варианты, а только самые популярные, поэтому даю возможность передать кастомный для выколотого случая.

_"я бы правда добавил ещё явную проверку на тип ..."_
  `EVO_DROPDOWN_POSITION_DESCRIPTION` - четкая конструкция, если переданное значение не будет соответствовать какому-либо ключу - ничего страшного не произойдет

2023-01-18 18:09 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-dropdown/evo-dropdown.component.ts
> +    @Output() isOpenChange = new EventEmitter<boolean>();
так не получится, в этом классе есть метод с именем `open`, да и я считаю, что у флагов должны быть имена, по которым можно понять, что это флаг

2023-01-18 18:52 UTC, harlamenko commented on projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navigation-item/evo-navbar-item.component.html
> +<ng-container *evoLet="$any(item) as linkItem">
```
  Property 'href' does not exist on type 'NavItemMainInfo & NavItemRouterLink'.

    3     *ngIf="item.href; else routerLink"
                      ~~~~

      projects/evo-ui-kit/src/lib/components/evo-navbar/evo-navbar-item/evo-navbar-item.component.ts:8:18
        8     templateUrl: './evo-navbar-item.component.html',
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component EvoNavbarItemComponent.

```

2023-01-20 08:10 UTC, merged

2023-01-20 08:30 UTC, andreymatveev commented
:tada: This PR is included in version 5.73.0 :tada:

The release is available on:
- [GitHub release](https://github.com/evotor/Evo-UI-Kit/releases/tag/v5.73.0)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: