Add dynamic columns
evotor/Evo-UI-Kit pull request #668
Opened 2020-11-25 10:27 UTC by ms-dosx86

Added ability to dynamically hide/show specified table columns. Now it's possible to pass an array of visible columns into `evo-table` like this `<evo-table [visibleColumns]="visibleColumns"></evo-table>`. For backward compatibility or if you just don't need this functionality, it's possible to omit the `visibleColumns` input and all columns should be visible by default.

2020-12-01 04:25 UTC, andreymatveev requested changes

2020-12-01 04:25 UTC, andreymatveev commented on projects/evo-ui-kit/src/lib/components/evo-table/evo-table/evo-table.component.ts
> +        if ('visibleColumns' in changes) {
Почему бы не использовать сеттер на `@Input('visibleColumns')`, чтобы не дёргать перестройку при изменении любого свойства?

2020-12-01 04:27 UTC, andreymatveev commented
Можешь заодно синхронизировать внешний вид таблиц с [макетами](https://www.figma.com/file/TJMwN4a8wGEvVYTKQpUAbgC0/Evotor-UI-Kit?node-id=2591%3A7211&viewport=1459%2C-7872%2C0.6244484782218933)? Сейчас боковые внутренние отступы слишком большие. Ну, и, может, ещё что-то найдёшь. По всем сомнениям можешь писать мне.

2020-12-02 06:05 UTC, ms-dosx86 commented on projects/evo-ui-kit/src/lib/components/evo-table/evo-table/evo-table.component.ts
> +        if ('visibleColumns' in changes) {
Здесь if для того и добавлен, чтобы не делать все это при изменении любого свойства. Это то же самое, что и использовать сеттер.

2020-12-02 06:35 UTC, andreymatveev commented on projects/evo-ui-kit/src/lib/components/evo-table/evo-table/evo-table.component.ts
> +        if ('visibleColumns' in changes) {
А зачем делать проверку каждый раз? Хук OnChanges имеет смысл использовать, когда есть зависимости от нескольких пропов или тебе нужны данные о предыдущих значениях. Здесь же всё примитивно.

2021-04-09 11:35 UTC, ms-dosx86 commented
@andreymatveev поправил отступы и высоту как в макете

2021-04-12 04:40 UTC, andreymatveev approved these changes

2021-04-12 10:31 UTC, closed without merging