Feature/evo accordion
evotor/Evo-UI-Kit pull request #766
Opened 2021-02-08 09:40 UTC by androfsky

2021-02-09 11:28 UTC, andreymatveev requested changes

2021-02-12 07:18 UTC, andreymatveev approved these changes
@androfsky Супер!

2021-02-12 07:18 UTC, andreymatveev commented on projects/evo-ui-kit/src/lib/components/evo-accordion/evo-accordion-content/evo-accordion-content.component.ts
> +    constructor(@Optional() private evoIsExpandedDirective: EvoIsExpandedDirective,
```
constructor(
    @Optional() private evoIsExpandedDirective: EvoIsExpandedDirective,
    private evoExpandedService: EvoExpandedService,
) {
}
```

2021-02-12 07:18 UTC, andreymatveev commented on projects/evo-ui-kit/src/lib/components/evo-accordion/evo-accordion-title/evo-accordion-title.component.html
> +        <evo-icon class="evo-accordion-title__expander"
```
<evo-icon 
    class="evo-accordion-title__expander"
    shape="expand"
    [evoUiClass]="{'expanded': isExpanded$ | async}"
></evo-icon>
```

2021-02-12 12:08 UTC, Komock approved these changes

2021-02-15 08:30 UTC, merged

2021-02-15 08:33 UTC, andreymatveev commented
:tada: This PR is included in version 5.29.0 :tada:

The release is available on:
- [GitHub release](https://github.com/evotor/Evo-UI-Kit/releases/tag/v5.29.0)
- `npm package (@versions/v5 dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: